"""add chef_notification_reads

Revision ID: 11abe59c7970
Revises: 545b9bd83db5
Create Date: 2025-12-01 20:10:26.962771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11abe59c7970'
down_revision: Union[str, Sequence[str], None] = '545b9bd83db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef_notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['chef_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chef_notification_reads_id'), 'chef_notification_reads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chef_notification_reads_id'), table_name='chef_notification_reads')
    op.drop_table('chef_notification_reads')
    # ### end Alembic commands ###
