"""Fix chef model

Revision ID: 545b9bd83db5
Revises: 77a775fda5bf
Create Date: 2025-12-01 15:43:01.711163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545b9bd83db5'
down_revision: Union[str, Sequence[str], None] = '77a775fda5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='chef_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_chefs_id'), 'chefs', ['id'], unique=False)
    op.create_foreign_key(None, 'chef_activity_logs', 'chefs', ['chef_id'], ['id'])
    op.create_foreign_key(None, 'chef_notifications', 'chefs', ['chef_id'], ['id'])
    op.create_foreign_key(None, 'order_status_history', 'chefs', ['changed_by_chef_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'chefs', ['assigned_chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_status_history', type_='foreignkey')
    op.drop_constraint(None, 'chef_notifications', type_='foreignkey')
    op.drop_constraint(None, 'chef_activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_chefs_id'), table_name='chefs')
    op.drop_table('chefs')
    # ### end Alembic commands ###
